---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Execute a kubectl command"
      ansible.builtin.command:
        cmd: kubectl get pods -A
      changed_when: false
